version: "3"

services:
  web:
    image: nmerm/timemachine-miiify
    build: .
    ports:
      - "80:8080"
      - "443:8080"
#    volumes:
#      - ./db:/home/miiify/db
    restart: always
#    logging:
#      driver: ${LOGGING_DRIVER:-json-file}
