apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  KONG_DATABASE_KEY: "off"
  KONG_PROXY_ACCESS_LOG_KEY: "/dev/stdout"
  KONG_ADMIN_ACCESS_LOG_KEY: "/dev/stdout"
  KONG_PROXY_ERROR_LOG_KEY: "/dev/stderr"
  KONG_ADMIN_ERROR_LOG_KEY: "/dev/stderr"
  KONG_PROXY_LISTEN_KEY: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
  KONG_ADMIN_LISTEN_KEY: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
  KONG_DECLARATIVE_CONFIG_KEY: "/etc/config/kong.yml"
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    services:
    - name: miiify
      url: https://miiify
      port: 8080
      routes:
      - name: root
        paths:
        - /v1
        - /
        preserve_host: true
        methods:
        - GET
        - HEAD
        - OPTIONS

    plugins:
    - name: cors
      service: miiify
      config: 
        origins:
        - '*'
        methods:
        - GET
        - HEAD
        - OPTIONS
        credentials: true
        max_age: 3600
